# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
  - image: circleci/node:8.9.4

jobs:

  build:
    <<: *defaults
    working_directory: ~/Battleship-dApp
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    <<: *defaults
    working_directory: ~/Battleship-dApp
    steps:
      - run:
          name: Running tests
          command: yarn truffle-tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build


